#define _CRT_SECURE_NO_WARNINGS
#include<iostream>
using namespace std;


class MyExcption //自定义异常类
{
public:
	void printError()
	{
		cout << "自定义异常" << endl;
	}
};
int myDevide(int a, int b)
{
	if (b == 0)
	{
		//return -1;

		//throw - 1;//抛出int类型
		//throw 3.14; //抛出double 类型

		throw MyExcption(); //抛出匿名对象
	}
	return a / b;
}

void test01()
{
	int a = 10;
	int b = 0;

	//int ret = myDevide(a, b); //无法分辨是非异常

	//C++中异常处理
	//try 和 catch 连用
	try
	{
		myDevide(a, b);
	}
	

	catch (MyExcption e)
	{
		e.printError();
	}
	
	catch (...)
	{
		//throw;  //如果出现异常，不处理
		cout << "类型异常捕获" << endl;
	}
}

int main()
{
	try
	{
		test01();
	}
	
	catch (int)
	{
		cout << "main中int类型异常捕获" << endl;
	}

	//如果异常未处理，那么成员terminate函数，使程序中断
	return EXIT_SUCCESS;
}
